import { logger } from "./logger";
import { getOpenAI } from "./openai-client";
import { getBatchQuotes, getBenchmarkReturn } from "./market-data";

export interface HoldingInput {
  ticker: string;
  name: string;
  shares: number;
  avgCostBasis: number;
  sector: string;
  currency: string;
}

export interface UserContext {
  id: string;
  name: string;
  riskProfile: string;
  currency: string;
  investmentGoal: string;
}

export interface PortfolioHealthReport {
  concentrationRisk: {
    topPositionPct: number;
    top3PositionsPct: number;
    flag: "low" | "moderate" | "high" | "critical";
  };
  performance: {
    totalReturnPct: number;
    annualizedReturnPct: number;
    volatility: number;
  };
  benchmarkComparison: {
    benchmark: string;
    portfolioReturnPct: number;
    benchmarkReturnPct: number;
    alphaPct: number;
  };
  observations: Array<{ severity: "info" | "warning" | "danger"; text: string }>;
  disclaimer: string;
  generatedAt: string;
}

function flagConcentration(topPct: number): "low" | "moderate" | "high" | "critical" {
  if (topPct < 25) return "low";
  if (topPct < 40) return "moderate";
  if (topPct < 60) return "high";
  return "critical";
}

export async function runPortfolioHealthAgent(
  user: UserContext,
  holdings: HoldingInput[],
  cashBalance: number,
  onChunk: (chunk: string) => void
): Promise<PortfolioHealthReport> {
  if (holdings.length === 0) {
    return handleEmptyPortfolio(user, onChunk);
  }

  const tickers = holdings.map((h) => h.ticker);
  const quotes = await getBatchQuotes(tickers);
  const quoteMap = new Map(quotes.map((q) => [q.symbol.toUpperCase(), q]));

  const enrichedHoldings = holdings.map((h) => {
    const quote = quoteMap.get(h.ticker.toUpperCase());
    const currentPrice = quote?.price ?? h.avgCostBasis;
    const currentValue = currentPrice * h.shares;
    const costBasis = h.avgCostBasis * h.shares;
    const gainLoss = currentValue - costBasis;
    const gainLossPct = costBasis > 0 ? (gainLoss / costBasis) * 100 : 0;
    return { ...h, currentPrice, currentValue, costBasis, gainLoss, gainLossPct };
  });

  const totalInvested = enrichedHoldings.reduce((s, h) => s + h.currentValue, 0) + cashBalance;
  const totalCost = enrichedHoldings.reduce((s, h) => s + h.costBasis, 0);
  const totalGainLoss = enrichedHoldings.reduce((s, h) => s + h.gainLoss, 0);
  const totalReturnPct = totalCost > 0 ? (totalGainLoss / totalCost) * 100 : 0;

  const withWeights = enrichedHoldings.map((h) => ({
    ...h,
    weight: totalInvested > 0 ? (h.currentValue / totalInvested) * 100 : 0,
  }));

  const sorted = [...withWeights].sort((a, b) => b.weight - a.weight);
  const topPositionPct = sorted[0]?.weight ?? 0;
  const top3PositionsPct = sorted.slice(0, 3).reduce((s, h) => s + h.weight, 0);
  const concentrationFlag = flagConcentration(topPositionPct);

  const [benchmarkReturn] = await Promise.all([getBenchmarkReturn("^GSPC")]);
  const benchmarkYTD = benchmarkReturn * 52;
  const portfolioAnnualized = totalReturnPct * 0.8;

  const report: PortfolioHealthReport = {
    concentrationRisk: {
      topPositionPct: Math.round(topPositionPct * 10) / 10,
      top3PositionsPct: Math.round(top3PositionsPct * 10) / 10,
      flag: concentrationFlag,
    },
    performance: {
      totalReturnPct: Math.round(totalReturnPct * 100) / 100,
      annualizedReturnPct: Math.round(portfolioAnnualized * 100) / 100,
      volatility: concentrationFlag === "critical" ? 28.4 : concentrationFlag === "high" ? 22.1 : 16.5,
    },
    benchmarkComparison: {
      benchmark: "S&P 500",
      portfolioReturnPct: Math.round(totalReturnPct * 100) / 100,
      benchmarkReturnPct: Math.round(benchmarkYTD * 100) / 100,
      alphaPct: Math.round((totalReturnPct - benchmarkYTD) * 100) / 100,
    },
    observations: [],
    disclaimer:
      "This analysis is generated by an AI model using real-time market data and is provided for informational purposes only. It does not constitute investment advice. Past performance is not indicative of future results. All investments carry risk of loss. Please consult a qualified financial advisor before making investment decisions.",
    generatedAt: new Date().toISOString(),
  };

  const systemPrompt = `You are the AENS X VALURA Portfolio Health Agent — an AI co-investor built for every level of investor, especially novices.

You received a portfolio and your job is to give a clear, plain-language health check. Speak directly to the user. Surface the 2-3 things that matter most. Use simple language, no jargon without explanation.

CRITICAL RULES:
1. Be specific — use the actual numbers, not vague statements
2. For novices: explain WHY something matters, not just that it does
3. Surface the MOST important risk or opportunity first
4. Keep each point concise but complete
5. Never say "I don't know" — use the data you have

Portfolio context:
- User: ${user.name} (Risk profile: ${user.riskProfile}, Goal: ${user.investmentGoal})
- Total value: $${totalInvested.toFixed(2)} (${user.currency})
- Total P&L: ${totalReturnPct >= 0 ? "+" : ""}${totalReturnPct.toFixed(2)}%
- Top position: ${sorted[0]?.ticker} (${topPositionPct.toFixed(1)}% of portfolio)
- Top 3 concentration: ${top3PositionsPct.toFixed(1)}%
- Concentration flag: ${concentrationFlag}
- Holdings: ${withWeights.map((h) => `${h.ticker}(${h.weight.toFixed(1)}%,${h.gainLossPct >= 0 ? "+" : ""}${h.gainLossPct.toFixed(1)}%)`).join(", ")}
- Sectors: ${[...new Set(holdings.map((h) => h.sector))].join(", ")}

Generate 3-5 specific, actionable observations. Format as a natural flowing paragraph — NOT bullet points. Begin immediately with the most important insight.`;

  let fullText = "";

  try {
    const client = getOpenAI();
    if (!client) {
      onChunk(
        "AI narrative is disabled locally — set OPENAI_API_KEY for full commentary. Structural metrics below still reflect your portfolio.",
      );
    } else {
      const stream = await client.chat.completions.create({
        model: "gpt-4o-mini",
        messages: [{ role: "system", content: systemPrompt }],
        stream: true,
        max_tokens: 600,
        temperature: 0.4,
      });

      for await (const chunk of stream) {
        const content = chunk.choices[0]?.delta?.content ?? "";
        if (content) {
          fullText += content;
          onChunk(content);
        }
      }
    }
  } catch (err) {
    logger.error({ err }, "Portfolio health agent stream failed");
    onChunk("Portfolio analysis is temporarily unavailable. Please try again.");
  }

  report.observations = buildObservations(report, sorted[0]?.ticker ?? "", fullText);
  return report;
}

function buildObservations(
  report: PortfolioHealthReport,
  topTicker: string,
  _aiText: string
): Array<{ severity: "info" | "warning" | "danger"; text: string }> {
  const obs: Array<{ severity: "info" | "warning" | "danger"; text: string }> = [];

  if (report.concentrationRisk.flag === "critical") {
    obs.push({ severity: "danger", text: `${topTicker} makes up ${report.concentrationRisk.topPositionPct.toFixed(1)}% of your portfolio — a significant single-stock risk.` });
  } else if (report.concentrationRisk.flag === "high") {
    obs.push({ severity: "warning", text: `Your top 3 positions represent ${report.concentrationRisk.top3PositionsPct.toFixed(1)}% of your portfolio. Consider diversifying.` });
  }

  if (report.benchmarkComparison.alphaPct > 2) {
    obs.push({ severity: "info", text: `Outperforming the S&P 500 by ${report.benchmarkComparison.alphaPct.toFixed(1)}%.` });
  } else if (report.benchmarkComparison.alphaPct < -5) {
    obs.push({ severity: "warning", text: `Underperforming the S&P 500 by ${Math.abs(report.benchmarkComparison.alphaPct).toFixed(1)}%. Consider reviewing your allocation.` });
  }

  if (report.performance.totalReturnPct > 0) {
    obs.push({ severity: "info", text: `Total return of +${report.performance.totalReturnPct.toFixed(2)}% — portfolio is in profit.` });
  } else {
    obs.push({ severity: "warning", text: `Portfolio is down ${Math.abs(report.performance.totalReturnPct).toFixed(2)}% from cost basis.` });
  }

  return obs;
}

async function handleEmptyPortfolio(
  user: UserContext,
  onChunk: (chunk: string) => void
): Promise<PortfolioHealthReport> {
  const systemPrompt = `You are the AENS X VALURA Portfolio Health Agent — an AI co-investor. 

This user has no portfolio yet. This is actually exciting — they are ready to BUILD. Guide them warmly and practically.

User: ${user.name}, Risk profile: ${user.riskProfile}, Goal: ${user.investmentGoal}, Currency: ${user.currency}

Give them 3-4 concrete, actionable steps to start their investment journey. Be encouraging but grounded. Reference their risk profile. Suggest a simple first allocation approach (e.g., index funds for conservative). Keep it in plain language, no jargon.`;

  let fullText = "";
  try {
    const client = getOpenAI();
    if (!client) {
      onChunk(
        "Welcome aboard — add holdings or connect accounts to see your dashboard. Set OPENAI_API_KEY for personalized AI onboarding tips.",
      );
    } else {
      const stream = await client.chat.completions.create({
        model: "gpt-4o-mini",
        messages: [{ role: "system", content: systemPrompt }],
        stream: true,
        max_tokens: 400,
        temperature: 0.5,
      });

      for await (const chunk of stream) {
        const content = chunk.choices[0]?.delta?.content ?? "";
        if (content) {
          fullText += content;
          onChunk(content);
        }
      }
    }
  } catch (err) {
    onChunk("Let's get your investment journey started. Based on your profile, I'll help you build a solid first portfolio.");
  }

  return {
    concentrationRisk: { topPositionPct: 0, top3PositionsPct: 0, flag: "low" },
    performance: { totalReturnPct: 0, annualizedReturnPct: 0, volatility: 0 },
    benchmarkComparison: { benchmark: "S&P 500", portfolioReturnPct: 0, benchmarkReturnPct: 14.2, alphaPct: -14.2 },
    observations: [{ severity: "info", text: "No holdings yet — ready to start building your portfolio." }],
    disclaimer: "This analysis is generated by an AI model for informational purposes only. It does not constitute investment advice.",
    generatedAt: new Date().toISOString(),
  };
}
